
server:
  port: ${PORT:8080}

credit:
  limit: 200

app:
  jwt:
    secret: ${JWT_SECRET}

#logging:
 # level:
  #  root: DEBUG

spring:
  application:
    name: finalcase

  datasource:
    url: jdbc:postgresql://localhost:5432/finalcase
    username: postgres
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true    # Sorguyu okunaklı bicimde (satır satır) yazar
        use_sql_comments: true

