
server:
  port: ${PORT:8080}

credit:
  limit: ${CREDIT_LIMIT}

app:
  jwt:
    secret: ${JWT_SECRET}

#logging:
 # level:
  #  root: DEBUG

spring:
  application:
    name: finalcase

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true    # Sorguyu okunaklı bicimde (satır satır) yazar
        use_sql_comments: true

